### ISSUE TITLE
Meta fields for Publications

### ISSUE THREAD

**Issue by slocker3** [happyprime/organizational#13]
We could use a few meta fields for publications:

- [x] Journal name
- [x] Publication date
- [x] Publication issue (example: `2022: Volume 6, Issue 9, September 2022, nzac132`)
- [x] Authors (this is different than associated people)
- [x] Link to publication (URL)*

** *Link to publication (url)**
We need to have a block binding variation of this so we can use it to link users directly to the publication instead of to the single post type.

**Comment by jeremyfelt** [comment]
> We need to have a block binding variation of this so we can use it to link users directly to the publication instead of to the single post type.

This should be exposed directly as the captured meta already.
